### ISSUE TITLE
Pinning the base theme results in console log errors

### ISSUE THREAD

**Issue by Bonkles** [OvertureMaps/io-site#140]
### Description

```
Error: layers.base_land_use_point_label.paint.text-halo-color: color expected, undefined found
    at Object.xi [as t] (index-BmW6-tk6.js:22105:133093)
    at ne (index-BmW6-tk6.js:22109:111416)
    at he._validate (index-BmW6-tk6.js:22109:131966)
    at he.addLayer (index-BmW6-tk6.js:22109:123589)
    at t.Map.addLayer (index-BmW6-tk6.js:22109:399717)
    at createLayer (index-BmW6-tk6.js:1989:13)
    at Layer$1 (index-BmW6-tk6.js:2025:9)
    at Xh (index-BmW6-tk6.js:360:137)
    at dj (index-BmW6-tk6.js:390:259)
    at Wk (index-BmW6-tk6.js:485:88)
```    

### Steps to reproduce

go to overturemaps.org/canary and then open the theme selector and pin the Base theme.  You will see the above. 

### The browser URL at the time you encountered the bug

n/a

**Comment by bdon** [comment]
`activeColor` needs to be assigned to the rest of the objects in this file where it's missing:

https://github.com/OvertureMaps/io-site/blob/main/site/src/Layers.js#L69

**Comment by Bonkles** [comment]
Dupe of #148, which is now closed. Closing this!
